---
# This role will install Duply to perform automated backups.
# There will probably be some variables necessary for the 
# keys that will be needed.
#

- name: Install duply package
  apt: pkg=duply state=present

- name: Create /etc/duply/default directory
  file: >
    dest=/etc/duply/default
    state=directory
    owner=root
    group=root
    mode=0700
#     recurse=yes

- name: Copy GnuPG key pair file
  copy: >
    src={{ duply_prep_directory }}/gpgkeys.asc
    dest=/etc/duply/default/
    owner=root
    group=root
    mode=0600
  notify:
    - Import GnuPG keys

# This task uses the duply_profile_template_directory variable
# to allow the user to prefix a path to a directory containing the
# files listed under with_items. All 4 files must exist at this path.
# The path listed in duply_profile_template_directory must end with
# a '/' for this to work.
# TODO: make it work with or without the slash. Possibly using a 
# default variable that applies the path filter and supplies a default
# value that is an empty string.
- name: Copy conf.j2 for Duply default profile
  template: >
    src={{ duply_profile_template_directory }}{{ item }}
    dest=/etc/duply/default/
    owner=root
    group=root
    mode=0600
  with_items:
    - conf.j2
    - exclude.j2
    - pre.j2
    - post.j2

- name: Generate ssh key for root
  user: >
    name=root
    generate_ssh_key=yes
  register: root_ssh_key

- debug: var=root_ssh_key.ssh_public_key

- name: Add backup target's SSH host key to /root/.ssh/known_hosts
  lineinfile: >
    dest=/root/.ssh/known_hosts
    create=yes
    mode=0644
    regexp="^{{ item }}"
    line="{{ item  + ' ' +  target_ssh_host_key_type + ' ' + target_ssh_host_key }}"
  with_items:
    - "{{ target_hostname }}"
    - "{{ target_ip + ',' + target_hostname }}"

# " So that the values are logged:
- debug: var=target_ssh_host_key_type
- debug: var=target_hostname
- debug: var=target_ip
- debug: var=target_ssh_host_key

- name: Duply full backup
  command: duply default full
  when: duply_suppress_backup is not defined

- name: Add nightly Duply backup to cron
  cron: >
    name=duply_nightly
    hour=3
    minute=10
    job="duply default backup"
    user=root
    state=present

- name: Add weekly Duply full backup to cron
  cron: >
    name=duply_weekly
    hour=5
    minute=0
    weekday=0
    job="duply default full"
    user=root
    state=present

- name: Add weekly Duply purge of old backups to cron
  cron: >
    name=duply_purge
    hour=2
    minute=0
    weekday=4
    job="duply default purge-full --force"
    user=root
    state=present

