---
# Defaults for MySQL server
#

# TODO: use password lookup
mysql_root_password: "{{ lookup('password', inventory_dir + '/passwords/' + ansible_fqdn + '/mysql_root length=64 chars=ascii,digits') }}"
mysql_dumpdb_password: "{{ lookup('password', inventory_dir + '/passwords/' + ansible_fqdn + '/mysql_dumpdb length=64 chars=ascii,digits') }}"
