---
# The common role handles the firewall and a few other common details like
# NTP and configuring sshd.

# TODO: replace my wonderful iptables-restore template with a basic
# installation of 'ufw', and use the new 'ufw' Ansible module in other
# roles to configure their own firewall rules.

#
# Note that these variables will be strings of "True" or "False" not
# actually boolean values. The get method is used on the groups dictionary
# to prevent KeyError exception if the inventory does not contain that
# group name.
firewall_unblock:
  mail_server: "{{ inventory_hostname in groups.get('mail_server', []) }}"
  name_server: "{{ inventory_hostname in groups.get('name_server', []) }}"
  web_server: "{{ inventory_hostname in groups.get('web_server', []) }}"
  monit: "{{ inventory_hostname in groups.get('name_server', []) }}"


