---
# The common role handles the firewall.

# Note that these variables will be strings of "True" or "False" not
# actually boolean values.
firewall_unblock:
  mailserver: "{{ inventory_hostname in groups['mail_server'] }}"
  nameserver: "{{ inventory_hostname in groups['name_server'] }}"
  monit: "{{ inventory_hostname in groups['monit'] }}"


