---
# The common role handles the firewall.

# Note that these variables will be strings of "True" or "False" not
# actually boolean values.
firewall_unblock:
  mail_server: "{{ inventory_hostname in groups['mail_server'] }}"
  name_server: "{{ inventory_hostname in groups['name_server'] }}"
  web_server: "{{ inventory_hostname in groups['web_server'] }}"
  monit: "{{ inventory_hostname in groups['monit'] }}"


