---
- name: Install Apache 
  apt: pkg=apache2-mpm-{{ apache2_mpm }} state=present

- name: Disable unnecessary Apache modules
  file: >
    path=/etc/apache2/mods-enabled/{{ item }}
    state=absent
  with_items:
    - cgi.load
    - autoindex.conf
    - autoindex.load
  notify: Restart Apache2

- name: Enable mod_ssl
  file: >
    dest=/etc/apache2/mods-enabled/{{ item }}
    src=/etc/apache2/mods-available/{{ item }}
    state=link
  with_items:
    - ssl.load
    - ssl.conf
  notify: Restart Apache2
