---

tripwire_local_password: "{{ lookup('password', inventory_dir + '/passwords/' + ansible_fqdn + '/tripwire_local') }}"
tripwire_site_password: "{{ lookup('password', inventory_dir + '/passwords/' + ansible_fqdn + '/tripwire_site') }}"
