---

tripwire_local_password: "{{ lookup('password', 'passwords/' + ansible_fqdn + '/tripwire_local') }}"
tripwire_site_password: "{{ lookup('password', 'passwords/' + ansible_fqdn + '/tripwire_site') }}"
