---
# This file contains some default values for the variables used by this role.

dkim_install: false
root_email_alias: root@{{ ansible_fqdn }}

# Enable monitoring with monit by default.
# This variable is used by the monit role.
monit_postfix: true
monit_dovecot: true

