---
# This role installs the BIND DNS server.
# It requires some host variables.

- name: Install bind9 package
  apt: pkg=bind9 state=present
  notify: Enable BIND at boot

- name: Install resolvconf
  apt: pkg=resolvconf state=present

- name: Tell BIND to use resolvconf in /etc/default/bind9
  lineinfile: >
    dest=/etc/default/bind9
    regexp="RESOLVCONF"
    line="RESOLVCONF=yes"
    state=present
  notify:
    - Restart BIND

- name: Copy named.conf.local.j2 template
  template: >
    src={{ dns_type }}.named.conf.local.j2
    dest=/etc/bind/named.conf.local
    owner=root
    group=bind
    mode=0640
  notify:
    - Reload BIND config

- name: Copy named.conf.options.j2 template
  template: >
    src=named.conf.options.j2
    dest=/etc/bind/named.conf.options
    owner=root
    group=bind
    mode=0640
  notify:
    - Reload BIND config

- name: Create /etc/bind/masters on DNS master server
  when: dns_type == "master"
  file: > 
    dest=/etc/bind/masters
    state=directory
    owner=root
    group=bind
    mode=0770
  notify:
    - Reload BIND config

- name: Copy zone files to master DNS server
  when: dns_type == "master"
  copy: >
    src={{ item }}
    dest=/etc/bind/masters/
    owner=root
    group=bind
    mode=0660
  with_fileglob:
    - "{{ dns_zone_source_directory }}/*"
  tags:
    - zone_files
  notify:
    - Reload BIND config


