---
# This file contains default values for some of the variables used by this role.
# There are other variables that need to be set that do not have defaults:
#  - duply_gpg_key: ID of GPG key that duply will sign backups with
#  - duply_target: the URL duply should send backups to


# TODO: is this variable actually used?
duply_cron: "30 4 * * 0"

duply_suppress_backup: true

duply_prep_directory: files/duply
duply_profile_template_directory: ""
duply_restore_tarballs: files/duply/restore_profiles

target_ssh_host_key_type: "ecdsa-sha2-nistp256"
target_hostname: "{{ hostvars[groups['archive'][0]].ansible_hostname }}"
target_ip: "{{ hostvars[groups['archive'][0]].ansible_default_ipv4.address }}"
target_ssh_host_key: "{{ hostvars[groups['archive'][0]].ansible_ssh_host_key_ecdsa_public }}"

duply_target_url: "ssh://{{ ansible_hostname }}@{{ target_hostname }}"

root_ssh_key_file: "/root/.ssh/ansible"
