---

- name: Install awstats
  apt: pkg=awstats state=present

- name: Install python-passlib
  apt: pkg=python-passlib state=present

- name: Create awstats user for reading Apache2 logs
  user: >
    name=awstats
    system=yes
    groups=adm,www-data
    state=present

- name: Add www-data to awstats group
  user: >
    name=www-data
    append=yes
    groups=awstats

- name: htpasswd file for awstats
  htpasswd: >
    name=awstats 
    state=present 
    path=/etc/awstats/htpasswd 
    password={{ awstats_htpasswd }}
    owner=root
    group=www-data
    mode=0640

- name: Copy awstats vhost conf to Apache2
  template: >
    src=apache2/awstats-vhost.conf.j2
    dest=/etc/apache2/sites-available/awstats.conf
    owner=root
    group=root
    mode=0664
  notify: Restart Apache2

- name: Create symlink for awstats-vhost.conf in /etc/apache2/sites-enabled
  file: >
    src=/etc/apache2/sites-available/awstats.conf
    dest=/etc/apache2/sites-enabled/awstats.conf
    state=link
  notify: Restart Apache2

- name: Enable group write permission on awstats directories
  file: >
    path={{ item }}
    mode=0770
  with_items:
    - /var/cache/awstats
    - /var/lib/awstats

- name: Update /etc/cron.d/awstats to run as awstats user
  template: >
    src=cron/awstats.j2
    dest=/etc/cron.d/awstats
    owner=root
    group=root
    mode=0644

- name: Delete /etc/awstats/awstats.conf
  file: >
    path=/etc/awstats/awstats.conf
    state=absent

- name: Copy awstats.awstats.conf.j2 for tracking the stats site
  template: >
    src=awstats/awstats.awstats.conf.j2
    dest=/etc/awstats/awstats.awstats.conf
    owner=root
    group=root
    mode=0644

- name: Copy awstats.conf.local.j2 for system wide config
  template: >
    src=awstats/awstats.conf.local.j2
    dest=/etc/awstats/awstats.conf.local
    owner=root
    group=root
    mode=0644
