---

- name: Install MoinMoin and libapache2-mod-wsgi
  apt: pkg={{ item }} state=present
  with_items:
    - python-moinmoin
    - libapache2-mod-wsgi

- name: Enable NameVirtualHost on port 443 in Apache2
  lineinfile: >
    line="    NameVirtualHost *:443"
    insertafter="^\<IfModule mod\_ssl.c\>"
    state=present
    dest=/etc/apache2/ports.conf
  notify: Restart Apache2

- name: Add wiki system user
  user: name={{ item.name }} system=yes state=present
  with_items: moinmoin_wikis

- name: Create /var/local/moin
  file: >
    dest=/var/local/moin
    state=directory
    owner=root
    group=root
    mode=0755

- name: Create directories in /var/local/moin for wikis
  file: >
    dest=/var/local/moin/{{ item.name }}
    state=directory
    owner={{ item.name }}
    group={{ item.name }}
    mode=0700
  with_items: moinmoin_wikis
  notify: Copy MoinMoin data and underlay

- name: Create dummy /var/www/wiki directory
  file: >
    dest=/var/www/wiki
    state=directory
    owner=root
    group=www-data
    mode=0770

- name: Copy SSL certificates for wikis
  copy: >
    src={{ item.ssl_cert }}
    dest=/etc/ssl/local/moin-{{ item.name }}-cert.pem
    owner=root
    group=root
    mode=0644
  with_items: moinmoin_wikis
  when: item.ssl_cert is defined and item.ssl_cert
  notify: Restart Apache2

- name: Copy SSL private keys for wikis
  copy: >
    src={{ item.ssl_key }}
    dest=/etc/ssl/local/private/moin-{{ item.name }}-key.pem
    owner=root
    group=root
    mode=0600
  with_items: moinmoin_wikis
  when: item.ssl_cert is defined and item.ssl_cert
  notify: Restart Apache2

- name: Copy Apache vhost template
  template: >
    src=apache2/moinmoin-vhost.conf.j2
    dest=/etc/apache2/sites-available/moin-{{ item.name }}.conf
    owner=root
    group=root
    mode=0600
  with_items: moinmoin_wikis
  notify: Restart Apache2

- name: Add vhost to sites-enabled
  file: >
    src=/etc/apache2/sites-available/moin-{{ item.name }}.conf
    dest=/etc/apache2/sites-enabled/moin-{{ item.name }}.conf
    state=link
  with_items: moinmoin_wikis
  notify: Restart Apache2

- name: Copy "mywiki.py" templates to /etc/moin
  template: >
    src=moin/mywiki.py.j2
    dest=/etc/moin/{{ item.name }}.py
    owner=root
    group=root
    mode=0644
  with_items: moinmoin_wikis
  notify: Restart Apache2

- name: Copy wikilist.j2 and farmconfig.py.j2 and moin.wsgi.j2 templates to /etc/moin/
  template: >
    src=moin/{{ item }}.j2
    dest=/etc/moin/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - wikilist
    - farmconfig.py
    - moin.wsgi
  notify: Restart Apache2
