---
# This role started out using msmtp-mta.
# It has since been switched to use Postfix with a null mailer
# configuration.
#
# TODO: allow user to specify relay host and auth details with
# variables

- name: Check for presence of /usr/sbin/postfix
  stat: path=/usr/sbin/postfix
  register: postfix_bin

- name: preseed Postfix for "No configuration"
  shell: echo "postfix postfix/main_mailer_type select No configuration" | debconf-set-selections
  when: postfix_bin.stat.exists == False

- name: Install Postfix
  apt: pkg=postfix state=present

- name: Remove exim4-base and exim4-config
  apt: pkg={{ item }} state=absent
  with_items:
    - exim4-base
    - exim4-config

- name: Copy /etc/postfix/main.cf template
  template: >
    src=postfix/main.cf.j2
    dest=/etc/postfix/main.cf
    owner=root
    group=root
    mode=0644
  notify:
    - Restart Postfix

- name: Copy SMTP client authentication map template
  template: >
    src=postfix/sasl_passwd.j2
    dest=/etc/postfix/sasl/sasl_passwd
    owner=root
    group=root
    mode=0600
  when: >
    mail_client_relayhost is defined and mail_client_relayhost
    and mail_client_username is defined and mail_client_username
    and mail_client_password is defined and mail_client_password
  notify:
    - Run postmap on /etc/postfix/sasl/sasl_passwd
    - Restart Postfix

- name: Copy /etc/aliases .j2 template
  template: >
    src=aliases.j2
    dest=/etc/aliases
    owner=root
    group=root
    mode=0644
  notify:
    - Run postalias
    - Restart Postfix
