---
# This role started out using msmtp-mta.
# It has since been switched to use Postfix with a null mailer
# configuration.
#
# TODO: allow user to specify relay host and auth details with
# variables

- name: Check for presence of /usr/sbin/postfix
  stat: path=/usr/sbin/postfix
  register: postfix_bin

- name: preseed Postfix for "No configuration"
  shell: echo "postfix postfix/main_mailer_type select No configuration" | debconf-set-selections
  when: postfix_bin.stat.exists == False

- name: Install Postfix
  apt: pkg={{ item }} state=present
  with_items:
    - postfix
#    - ca-certificates

- name: Remove exim4-base and exim4-config
  apt: pkg={{ item }} state=absent
  with_items:
    - exim4-base
    - exim4-config
    - msmtp-mta

- name: Copy /etc/postfix/main.cf template
  template: >
    src=postfix/main.cf.j2
    dest=/etc/postfix/main.cf
    owner=root
    group=root
    mode=0644

- name: Copy /etc/aliases .j2 template
  template: >
    src=aliases.j2
    dest=/etc/aliases
    owner=root
    group=root
    mode=0644
  notify:
    - Run postalias
