---
# handlers for the postgres role

- name: Create PostgreSQL superuser role ansiblepg
  postgresql_user: name=ansibledb password=password state=present role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER
  sudo: yes
