---
# These handlers are to be run after new configuration files have
# been sent to the server.

- name: Reload sshd config
  service: name=ssh state=reloaded

- name: Reload iptables rules
  command: /etc/network/if-pre-up.d/firewall
