---
# handlers for the duply backup installation
#

- name: Append /root/.ssh/known_hosts
  shell: "ssh-keyscan -H archive.deptadapt.org >> /root/.ssh/known_hosts"

- name: Copy GnuPG key pair file
  copy: >
    src={{ duply_keys_directory }}/{{ duply_gpg_keys_file }}
    dest=/etc/duply/default/
    owner=root
    group=root
    mode=0600

- name: Import GnuPG keys
  shell: gpg --allow-secret-key-import --trust-model always --import /etc/duply/default/both.asc

- name: Duply full backup
  command: duply default backup

- name: Make tarball of duply profile
  shell: "tar cvf /tmp/{{ ansible_fqdn }}.duply-profile.tar /etc/duply/default"

- name: Fetch the duply profile
  fetch: >
    flat=yes
    src=/tmp/{{ ansible_fqdn }}.duply-profile.tar
    dest={{ duply_profiles_directory }}/
    fail_on_missing=yes

- name: Remove tarball of duply profile
  command: rm /tmp/{{ ansible_fqdn }}.duply-profile.tar

