---
# This role contains the common elements to all systems

# This task commented out for testing purposes (too slow)
# - name: Make sure APT is up to date
#   apt: update_cache=yes upgrade=yes

- name: Install NTP service
  apt: pkg=ntp state=latest

- name: Install harden-servers
  apt: pkg=harden-servers state=latest

- name: Copy Tripwire debconf database
  template: src=tripwire-debconf-config.dat.j2 dest=/run/shm/tripwire-debconf-config.dat owner=root mode=0600
  
- name: Install harden package
  environment:
    DEBCONF_DB_FALLBACK: "File{/run/shm/tripwire-debconf-config.dat}"
  apt: pkg=harden state=latest
  notify:
    - Copy Tripwire policy text file twpol.txt
    - Generate Tripwire policy
    - Generate Tripwire initial database

- name: Remove Tripwire debconf database
  command: rm /run/shm/tripwire-debconf-config.dat

# Generating the Tripwire policy and initial database should only
# be done if Tripwire needed to be installed.


