---
# This role contains the common elements to all systems

# This task commented out for testing purposes (too slow)
# - name: Make sure APT is up to date
#   apt: update_cache=yes upgrade=yes

- name: Install NTP service
  apt: pkg=ntp state=latest

- name: Install harden-servers
  apt: pkg=harden-servers state=latest


