#!/bin/sh

# This script needs to look for files in /var/local/ and delete them.
# The database dump scripts that are called (if they exist) in the pre 
# script leave their dumps in /var/local

exit 0
