---
# This role will install the PostgreSQL database to the system.
# It will also set a password for the postgres role to be used by
# other plays when creating 
# 
# Note the LANG and LC_ALL environment variables are set so that
# PostgreSQL will generate the initial database cluster in UTF-8
# because without them it defaults to SQL-ASCII. There might be an
# Ansible variable I can use to default this to the master's locale.

- name: Install PostgreSQL database server
  environment:
    LANG: en_CA.UTF-8 
    LC_ALL: en_CA.UTF-8 
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql-client
    - postgresql
    - python-psycopg2

# We also deploy a script that will dump the contents
# of all databases to a text file.
- name: Copy postgresql_dump_all.sh.j2 to /usr/local/sbin
  template: >
    src=postgresql_dump_all.sh.j2
    dest=/usr/local/sbin/postgresql_dump_all.sh
    owner=postgres
    group=postgres
    mode=0770

- name: Make sure /var/local/pgsql_dumps exits
  file: >
    dest=/var/local/pgsql_dumps
    state=directory
    owner=postgres
    group=postgres
    mode=0700


    
