---
# This role installs the Debian harden package, which includes a bunch
# of security related packages.
#
# One of thos packages, Tripwire, needs special steps taken to get the
# passphrases for the encryption keys generated properly. Instead of 
# preseeding the debconf database, a database fragment is included that
# contains the passphrase, and is used with the DEBCONF_DB_FALLBACK
# environment variable.

- name: Check for presence of /usr/sbin/tripwire
  stat: path=/usr/sbin/tripwire
  register: tripwire_bin

- name: Copy Tripwire debconf database
  template: >
    src=tripwire-debconf-config.dat.j2
    dest=/run/shm/tripwire-debconf-config.dat
    owner=root
    mode=0600
  when: tripwire_bin.stat.exists == False
  
- name: Install harden package
  environment:
    DEBCONF_DB_FALLBACK: "File{/run/shm/tripwire-debconf-config.dat}"
  apt: pkg=harden state=present
  notify:
    - Copy Tripwire policy text file twpol.txt
    - Generate Tripwire policy
    - Generate Tripwire initial database

- name: Remove Tripwire debconf database
  file: path=/run/shm/tripwire-debconf-config.dat state=absent
