---
# This role installs MySQL server and sets the root password.

- name: Install mysql-server package
  apt: pkg={{ item }} state=present
  with_items:
    - mysql-server
    - python-mysqldb
  notify:
    - Set MySQL root password

- meta: flush_handlers

- name: Make sure dumpdb user exists
  mysql_user: >
    login_user=root
    login_password={{ mysql_root_password }}
    name=dumpdb
    password={{ mysql_dumpdb_password }}
    priv="*.*:SELECT"

- name: Make sure the mysql_dump_all.sh exists
  template: >
    src=mysql_dump_all.sh.j2
    dest=/usr/local/sbin/mysql_dump_all.sh
    owner=root
    group=root
    mode=0700

- name: Make sure /var/local/mysql_dumps exists
  file: >
    dest=/var/local/mysql_dumps
    state=directory
    owner=root
    group=root
    mode=0700

